title: B.E.L.F.A.G.O.R.
description: A mini-website about the Fablab electronics barter day
sitename: Belfagor
permalink: pretty
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME